name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run Type checks
        run: npm run type-check
